### ISSUE TITLE
The ability to change data folders without re-opening the program.

### ISSUE THREAD

**Issue by UWCreations** [OtherworldBob/ManiacEditor#12]
I've really wanted this because I sometimes choose the wrong mod to open and have to re-open the program. It's just kind of annoying having to do that, honestly.

**Comment by OtherworldBob** [comment]
Please give the latest release a go.
Ctrl + Alt + O, is the new keyboard shortcut to open a new Data Folder directly, bypassing the current info pop-up.
If you hit any problems, let me know!
