### ISSUE TITLE
Not updated to 1.05/Plus

### ISSUE THREAD

**Issue by Araraura** [OtherworldBob/ManiacEditor#25]
Just as title says, it's not updated.

**Comment by OtherworldBob** [comment]
The gun was jumped a little early over in Discord.
You can find a work-in-progress build here: https://ci.appveyor.com/project/OtherworldBob/maniaceditor/build/0.2.25.1/artifacts

I'd hope to release something a little more formally before too long.

**Comment by OtherworldBob** [comment]
Actually, you know what, let's just stick up on the main page: https://github.com/OtherworldBob/ManiacEditor/releases/tag/v0.2.25.1

The sooner any problems are found the better!
With that in mind, if you find any, please open another issue!
