### ISSUE TITLE
Stream Not Closed for GameConfig(string filename)

### ISSUE THREAD

**Issue by thesupersonic16** [OtherworldBob/ManiacEditor#30]
`GameConfig(string filename)` at https://github.com/OtherworldBob/ManiacEditor/blob/master/RSDKv5/GameConfig.cs#L96

We are unable to close the Stream it opens, We shouldn't be keeping streams open when we are done, and with that constructor We have no access to the stream, which is an issue.
Write(string filename) seems to be using `using` which closes the stream at the end, But `GameConfig(string filename)` doesn't. I hope you can get this fixed as there is no point of having a broken constructor.

Also incase I confused anyone `GameConfig(Stream stream)` works fine as we create the Stream, thus allowing us to close it.

**Comment by OtherworldBob** [comment]
Per the above, merged #34, to resolve this one. 
Auto-build looks good to me, so closing this one.
