### ISSUE TITLE
Overlay a PNG File for Easy 1:1 Stage Recreation

### ISSUE THREAD

**Issue by CarJem** [OtherworldBob/ManiacEditor#7]
Take a map like this for say:
http://info.sonicretro.org/images/0/0b/S2_map_HPZ.png
Or one you export from Maniac.

There should be a way to have this displayed transparently, to make it easier to replicate stages. Especially with Mania Plus Right around the corner.

**Comment by OtherworldBob** [comment]
I can see this being incredibly useful for some people.
Alas this may also be straying into the area of code I know the least. 
One to think about, but one I'm not likely to get to soon.

**Comment by CarJem** [comment]
This is something I simply close, not only does this look hard, but it is a good way to copy stages. And in alot of cases that can be bad. There are other ways to do get around this, and I don't see any other Sonic Level editor having such a feature like this.
